version: '3.8'

services:
  spring-boot-registration-login:
    build: ./spring-boot-registration-login
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cloud1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: d3f4ult
      UPLOAD_DIR: /uploads
    volumes:
      - ./uploads:/uploads  # Maps host directory to container directory

  db:
    build: ./db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: d3f4ult
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
